### ISSUE TITLE
cv2.split(input_image)

### ISSUE THREAD

**Issue by CQSamBoom** [fengjian0106/hed-tutorial-for-document-scanning#66]
Traceback (most recent call last):
  File "train_hed.py", line 237, in <module>
    FLAGS.debug_image_dir, suffix='{}'.format(step))
  File "/home/huang/Sam_test/hed_egdedetector/hed-tutorial-for-document-scanning-master/hed-tutorial-for-document-scanning-master/util.py", line 69, in plot_and_save_image
    (b, g, r) = cv2.split(input_image)
ValueError: not enough values to unpack (expected 3, got 0)

有人救救孩子吗，完全按照作者的步骤进行，这里始终有问题，    input_image = cv2.imread(input_image_path)  这一步似乎没有生效，input_image显示是none，但是也没有报错，求好心人相助。

**Comment by fengjian0106** [comment]
input_image显示是none，那就是没有读取到图片文件，你应该检查一下 input_image_path路径是否有效，图片格式是否正确，opencv库是否有问题
